// Generated by `luca build-runtime`. Do not edit by hand.
// @ts-nocheck — the blob only exists after build-runtime has run

export const runtimeBlob: string | null = null

export const runtimeIndex: Array<{ path: string; offset: number; length: number }> = []
