/**
 * AUTO-GENERATED by scripts/generate-feature-barrel.ts — DO NOT EDIT.
 *
 * Regenerate with: bun run build:feature-barrel
 *
 * Adding a feature only requires the feature file itself (class + static
 * stability + Feature.register static block). This barrel supplies the
 * imports, re-exports, and the feature-id -> class interface the
 * container builds its Features type from.
 */

import { Memory } from "./features/agent-memory";
import { Assistant } from "./features/assistant";
import { AssistantsManager } from "./features/assistants-manager";
import { AutonomousAssistant } from "./features/autonomous-assistant";
import { BrowserUse } from "./features/browser-use";
import { ClaudeCode } from "./features/claude-code";
import { ClaudeController } from "./features/claude-controller";
import { CodingTools } from "./features/coding-tools";
import { ConversationHistory } from "./features/conversation-history";
import { Conversation } from "./features/conversation";
import { DocsReader } from "./features/docs-reader";
import { FileTools } from "./features/file-tools";
import { LucaCoder } from "./features/luca-coder";
import { McpBridge } from "./features/mcp-bridge";
import { ModelProviders } from "./features/model-providers";
import { OpenAICodex } from "./features/openai-codex";
import { OpenAPI } from "./features/openapi";
import { SkillsLibrary } from "./features/skills-library";
import { VoiceMode } from "./features/voice-mode";

export { Memory } from "./features/agent-memory";
export type { MemoryState, MemoryOptions, MemoryRecord, MemorySearchResult } from "./features/agent-memory";
export { Assistant } from "./features/assistant";
export type { AssistantState, AssistantOptions, AssistantForkOptions, ResearchJobState, ResearchJobOptions, ResearchJobEvents, ResearchJob } from "./features/assistant";
export { AssistantsManager } from "./features/assistants-manager";
export type { AssistantEntry, AssistantsManagerState, AssistantsManagerOptions } from "./features/assistants-manager";
export { AutonomousAssistant } from "./features/autonomous-assistant";
export type { AutoAssistantPermissionLevel, AutoAssistantPendingApproval, AutoAssistantToolBundleSpec, AutonomousAssistantState, AutonomousAssistantOptions } from "./features/autonomous-assistant";
export { BrowserUse } from "./features/browser-use";
export type { BrowserUseState, BrowserUseOptions } from "./features/browser-use";
export { ClaudeCode } from "./features/claude-code";
export type { ClaudeInitEvent, ClaudeAssistantMessage, ClaudeToolResult, ClaudeStreamEvent, ClaudeResultEvent, ClaudeEvent, ClaudeSession, McpStdioServer, McpHttpServer, McpSseServer, ClaudeCodeMcpServerConfig, FileLogLevel, ClaudeCodeState, ClaudeCodeOptions, RunOptions } from "./features/claude-code";
export { ClaudeController } from "./features/claude-controller";
export type { ClaudeControllerState, ClaudeControllerOptions } from "./features/claude-controller";
export { CodingTools } from "./features/coding-tools";
export { ConversationHistory } from "./features/conversation-history";
export type { TokenUsage, CostInfo, ConversationRecord, ConversationMeta, SearchOptions, ConversationHistoryOptions, ConversationHistoryState } from "./features/conversation-history";
export { Conversation } from "./features/conversation";
export type { Message, ContentPart, ConversationTool, ConversationMCPServer, ConversationAbortError, ConversationOptions, ConversationState, AskOptions, ForkOptions } from "./features/conversation";
export { DocsReader } from "./features/docs-reader";
export type { DocsReaderState, DocsReaderOptions } from "./features/docs-reader";
export { FileTools } from "./features/file-tools";
export { LucaCoder } from "./features/luca-coder";
export type { PermissionLevel, PendingApproval, ToolBundleSpec, LucaCoderState, LucaCoderOptions } from "./features/luca-coder";
export { McpBridge } from "./features/mcp-bridge";
export type { McpServerConfig, McpBridgeOptions, McpBridgeState } from "./features/mcp-bridge";
export { ModelProviders } from "./features/model-providers";
export type { ModelProviderApiMode, ModelProviderAuth, ModelProviderProfile, ModelProviderInlineInput, ModelProviderInput, ModelProviderResolveOptions, ModelMessage, ModelToolCall, ModelTool, ModelRequest, ModelResponse, ModelStreamEvent, ModelTransport, ResolvedModelProvider, OpenAIChatCompletionsTransport, OpenAIResponsesTransport, ClaudeSessionTransportOptions, OpenAICodexTransport, ClaudeSessionTransport } from "./features/model-providers";
export { OpenAICodex } from "./features/openai-codex";
export type { CodexItem, CodexItemEvent, CodexTurnEvent, CodexThreadEvent, CodexMessageEvent, CodexExecEvent, CodexEvent, CodexSession, OpenAICodexState, OpenAICodexOptions, CodexRunOptions } from "./features/openai-codex";
export { OpenAPI } from "./features/openapi";
export type { OpenAPIOptions, OpenAPIState, EndpointInfo, OpenAPIParameter, OpenAIFunctionDef, OpenAIToolDef } from "./features/openapi";
export { SkillsLibrary } from "./features/skills-library";
export type { SkillInfo, SkillsLibraryState, SkillsLibraryOptions } from "./features/skills-library";
export { VoiceMode } from "./features/voice-mode";
export type { VoiceModeOptions, VoiceModeState, VoiceConfig } from "./features/voice-mode";

export interface GeneratedAGIFeatures {
  assistant: typeof Assistant;
  assistantsManager: typeof AssistantsManager;
  autoAssistant: typeof AutonomousAssistant;
  browserUse: typeof BrowserUse;
  claudeCode: typeof ClaudeCode;
  claudeController: typeof ClaudeController;
  codingTools: typeof CodingTools;
  conversation: typeof Conversation;
  conversationHistory: typeof ConversationHistory;
  docsReader: typeof DocsReader;
  fileTools: typeof FileTools;
  lucaCoder: typeof LucaCoder;
  mcpBridge: typeof McpBridge;
  memory: typeof Memory;
  modelProviders: typeof ModelProviders;
  openaiCodex: typeof OpenAICodex;
  openapi: typeof OpenAPI;
  skillsLibrary: typeof SkillsLibrary;
  voiceMode: typeof VoiceMode;
}

/** Every registered feature class, keyed by class name — for use() loops and VM module seeding. */
export const generatedAgiFeatureExports = {
  Assistant,
  AssistantsManager,
  AutonomousAssistant,
  BrowserUse,
  ClaudeCode,
  ClaudeController,
  CodingTools,
  Conversation,
  ConversationHistory,
  DocsReader,
  FileTools,
  LucaCoder,
  McpBridge,
  Memory,
  ModelProviders,
  OpenAICodex,
  OpenAPI,
  SkillsLibrary,
  VoiceMode,
} as const;
