import { z } from 'zod'
import type { ContainerContext } from '../src/node'
import { CommandOptionsSchema } from '../src/schemas/base'
import { HELPER_CATEGORIES, CATEGORY_LABELS, isHelperCategory } from '../src/introspection/index'

export const argsSchema = CommandOptionsSchema.extend({})

const GENERATED_BLOCK_RE = /(<!-- BEGIN:GENERATED helper-tables[^>]*-->)[\s\S]*?(<!-- END:GENERATED helper-tables -->)/

function firstSentence(text: string): string {
	const clean = (text || '').trim().replace(/\s+/g, ' ')
	const match = clean.match(/^.*?[.!?](\s|$)/)
	return (match ? match[0] : clean).trim()
}

interface HelperRow {
	id: string
	kind: 'feature' | 'client' | 'server'
	category: string
	stability: string
	summary: string
}

/** Collect every registered helper's id/kind/category/stability/summary from live introspection. */
function collectHelperRows(container: any): HelperRow[] {
	const rows: HelperRow[] = []
	const registries: Array<{ name: string; kind: HelperRow['kind'] }> = [
		{ name: 'features', kind: 'feature' },
		{ name: 'clients', kind: 'client' },
		{ name: 'servers', kind: 'server' },
	]
	for (const { name, kind } of registries) {
		const registry = container[name]
		if (!registry?.available) continue
		for (const id of [...registry.available].sort()) {
			let Ctor: any
			try { Ctor = registry.lookup(id) } catch { continue }
			const intro = Ctor?.introspect?.()
			rows.push({
				id,
				kind,
				category: intro?.category || Ctor?.category || '',
				stability: intro?.stability || Ctor?.stability || '',
				summary: firstSentence(intro?.description || Ctor?.description || ''),
			})
		}
	}
	return rows
}

/** The generated "Features by Category" + Clients + Servers tables for SKILL.md. */
function generateHelperTables(rows: HelperRow[]): string {
	const features = rows.filter(r => r.kind === 'feature')
	const byCategory = new Map<string, HelperRow[]>()
	for (const f of features) {
		const key = f.category || 'other'
		if (!byCategory.has(key)) byCategory.set(key, [])
		byCategory.get(key)!.push(f)
	}
	const order = [
		...HELPER_CATEGORIES.filter(c => byCategory.has(c)),
		...[...byCategory.keys()].filter(c => !(HELPER_CATEGORIES as readonly string[]).includes(c)),
	]

	const featureRows = order.map(cat => {
		const label = isHelperCategory(cat) ? CATEGORY_LABELS[cat].label : 'Other'
		const description = isHelperCategory(cat) ? CATEGORY_LABELS[cat].description : 'Project-specific helpers'
		const names = byCategory.get(cat)!.map(f => `\`${f.id}\``).join(', ')
		return `| **${label}** | ${names} | ${description} |`
	})

	const clientRows = rows.filter(r => r.kind === 'client')
		.map(c => `| \`${c.id}\` | ${c.summary} |`)
	const serverRows = rows.filter(r => r.kind === 'server')
		.map(s => `| \`${s.id}\` | ${s.summary} |`)

	return [
		'### Features by Category',
		'',
		'| Category | Features | What they do |',
		'|----------|----------|--------------|',
		...featureRows,
		'',
		'### Clients',
		'',
		'| Client | Purpose |',
		'|--------|---------|',
		...clientRows,
		'',
		'### Servers',
		'',
		'| Server | Purpose |',
		'|--------|---------|',
		...serverRows,
	].join('\n')
}

/** The flat references/helper-index.md lookup table. */
function generateHelperIndex(rows: HelperRow[]): string {
	const tableRows = rows.map(r => {
		const label = isHelperCategory(r.category) ? r.category : (r.category || '—')
		return `| \`${r.id}\` | ${r.kind} | ${label} | ${r.stability || '—'} | ${r.summary} |`
	})
	return [
		'# Helper Index',
		'',
		'Every built-in helper in the luca container. Run `luca describe <name>` for full docs on any of them, or search by meaning with `luca describe --query "..."`.',
		'',
		'| Name | Kind | Category | Stability | Description |',
		'|------|------|----------|-----------|-------------|',
		...tableRows,
		'',
		'_Generated by `luca build-bootstrap` from live introspection data — do not edit by hand._',
		'',
	].join('\n')
}

async function buildBootstrap(options: z.infer<typeof argsSchema>, context: ContainerContext) {
	const container = context.container as any
	const fs = container.feature('fs')

	const sourceDir = 'docs/bootstrap'
	const outputPath = 'src/bootstrap/generated.ts'

	if (!fs.exists(sourceDir)) {
		console.log(`Source directory ${sourceDir} not found`)
		return
	}

	// 0. Regenerate the helper tables inside docs/bootstrap/SKILL.md (in place,
	// between the GENERATED markers) so the skill's category index can never
	// drift from the actual registered helpers.
	const helperRows = collectHelperRows(container)
	const skillPath = `${sourceDir}/SKILL.md`
	const skillSource = await fs.readFileAsync(skillPath)
	if (GENERATED_BLOCK_RE.test(skillSource)) {
		const updated = skillSource.replace(GENERATED_BLOCK_RE, `$1\n${generateHelperTables(helperRows)}\n$2`)
		if (updated !== skillSource) {
			await fs.writeFileAsync(skillPath, updated)
			console.log(`   regenerated helper tables in ${skillPath} (${helperRows.length} helpers)`)
		}
	} else {
		console.log(`   ⚠ no GENERATED helper-tables markers found in ${skillPath} — tables not regenerated`)
	}

	// 1. Collect top-level markdown files (SKILL.md, CLAUDE.md, etc.)
	const allFiles = await fs.readdir(sourceDir)
	const mdFiles = allFiles.filter((f: string) => f.endsWith('.md'))
	const entries: Record<string, string> = {}

	for (const file of mdFiles) {
		const content = await fs.readFileAsync(`${sourceDir}/${file}`)
		const name = file.replace(/\.md$/, '')
		entries[name] = content
		console.log(`   ${name}: ${content.length} chars`)
	}

	// 2. Collect template files (docs/bootstrap/templates/*)
	const templates: Record<string, string> = {}
	const templatesDir = `${sourceDir}/templates`
	if (fs.exists(templatesDir)) {
		const templateFiles = await fs.readdir(templatesDir)
		for (const file of templateFiles) {
			const content = await fs.readFileAsync(`${templatesDir}/${file}`)
			const name = file.replace(/\.[^.]+$/, '') // strip any extension
			templates[name] = content
			console.log(`   template/${name}: ${content.length} chars`)
		}
	}

	// 3. Collect docs/examples/*.md
	const examples: Record<string, string> = {}
	const examplesDir = 'docs/examples'
	if (fs.exists(examplesDir)) {
		const exampleFiles = (await fs.readdir(examplesDir)).filter((f: string) => f.endsWith('.md'))
		for (const file of exampleFiles) {
			const content = await fs.readFileAsync(`${examplesDir}/${file}`)
			examples[file] = content
			console.log(`   example/${file}: ${content.length} chars`)
		}
	}

	// 4. Collect docs/tutorials/*.md
	const tutorials: Record<string, string> = {}
	const tutorialsDir = 'docs/tutorials'
	if (fs.exists(tutorialsDir)) {
		const tutorialFiles = (await fs.readdir(tutorialsDir)).filter((f: string) => f.endsWith('.md'))
		for (const file of tutorialFiles) {
			const content = await fs.readFileAsync(`${tutorialsDir}/${file}`)
			tutorials[file] = content
			console.log(`   tutorial/${file}: ${content.length} chars`)
		}
	}

	const escapeForTemplate = (s: string) => s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')

	const fileEntries = Object.entries(entries).map(([name, content]) =>
		`  ${JSON.stringify(name)}: \`${escapeForTemplate(content)}\``
	).join(',\n')

	const templateEntries = Object.entries(templates).map(([name, content]) =>
		`  ${JSON.stringify(name)}: \`${escapeForTemplate(content)}\``
	).join(',\n')

	const exampleEntries = Object.entries(examples).map(([name, content]) =>
		`  ${JSON.stringify(name)}: \`${escapeForTemplate(content)}\``
	).join(',\n')

	const tutorialEntries = Object.entries(tutorials).map(([name, content]) =>
		`  ${JSON.stringify(name)}: \`${escapeForTemplate(content)}\``
	).join(',\n')

	// 5. Generated reference docs written to .claude/skills/luca-framework/references/
	const references: Record<string, string> = {
		'helper-index.md': generateHelperIndex(helperRows),
	}
	console.log(`   reference/helper-index.md: ${references['helper-index.md']!.length} chars (${helperRows.length} helpers)`)
	const referenceEntries = Object.entries(references).map(([name, content]) =>
		`  ${JSON.stringify(name)}: \`${escapeForTemplate(content)}\``
	).join(',\n')

	const output = `// Auto-generated bootstrap content
// Source: docs/bootstrap/*.md, docs/bootstrap/templates/*, docs/examples/*.md, docs/tutorials/*.md,
// plus reference docs generated from live introspection data.
//
// Do not edit manually. Run: luca build-bootstrap

export const bootstrapFiles: Record<string, string> = {
${fileEntries}
}

export const bootstrapTemplates: Record<string, string> = {
${templateEntries}
}

export const bootstrapExamples: Record<string, string> = {
${exampleEntries}
}

export const bootstrapTutorials: Record<string, string> = {
${tutorialEntries}
}

export const bootstrapReferences: Record<string, string> = {
${referenceEntries}
}
`

	fs.ensureFolder('src/bootstrap')
	await fs.writeFileAsync(outputPath, output)
	console.log(`\nGenerated ${outputPath}`)
}

export default {
	description: 'Bundle docs/bootstrap/*.md into src/bootstrap/generated.ts for the compiled binary',
	argsSchema,
	handler: buildBootstrap,
}
