import f0 from "figlet/importable-fonts/1Row.js";
import f1 from "figlet/importable-fonts/3-D.js";
import f2 from "figlet/importable-fonts/3D Diagonal.js";
import f3 from "figlet/importable-fonts/3D-ASCII.js";
import f4 from "figlet/importable-fonts/3x5.js";
import f5 from "figlet/importable-fonts/4Max.js";
import f6 from "figlet/importable-fonts/5 Line Oblique.js";
import f7 from "figlet/importable-fonts/AMC 3 Line.js";
import f8 from "figlet/importable-fonts/AMC 3 Liv1.js";
import f9 from "figlet/importable-fonts/AMC AAA01.js";
import f10 from "figlet/importable-fonts/AMC Neko.js";
import f11 from "figlet/importable-fonts/AMC Razor.js";
import f12 from "figlet/importable-fonts/AMC Razor2.js";
import f13 from "figlet/importable-fonts/AMC Slash.js";
import f14 from "figlet/importable-fonts/AMC Slider.js";
import f15 from "figlet/importable-fonts/AMC Thin.js";
import f16 from "figlet/importable-fonts/AMC Tubes.js";
import f17 from "figlet/importable-fonts/AMC Untitled.js";
import f18 from "figlet/importable-fonts/ANSI Regular.js";
import f19 from "figlet/importable-fonts/ANSI Shadow.js";
import f20 from "figlet/importable-fonts/ASCII New Roman.js";
import f21 from "figlet/importable-fonts/Acrobatic.js";
import f22 from "figlet/importable-fonts/Alligator.js";
import f23 from "figlet/importable-fonts/Alligator2.js";
import f24 from "figlet/importable-fonts/Alpha.js";
import f25 from "figlet/importable-fonts/Alphabet.js";
import f26 from "figlet/importable-fonts/Arrows.js";
import f27 from "figlet/importable-fonts/Avatar.js";
import f28 from "figlet/importable-fonts/B1FF.js";
import f29 from "figlet/importable-fonts/Banner.js";
import f30 from "figlet/importable-fonts/Banner3-D.js";
import f31 from "figlet/importable-fonts/Banner3.js";
import f32 from "figlet/importable-fonts/Banner4.js";
import f33 from "figlet/importable-fonts/Barbwire.js";
import f34 from "figlet/importable-fonts/Basic.js";
import f35 from "figlet/importable-fonts/Bear.js";
import f36 from "figlet/importable-fonts/Bell.js";
import f37 from "figlet/importable-fonts/Benjamin.js";
import f38 from "figlet/importable-fonts/Big Chief.js";
import f39 from "figlet/importable-fonts/Big Money-ne.js";
import f40 from "figlet/importable-fonts/Big Money-nw.js";
import f41 from "figlet/importable-fonts/Big Money-se.js";
import f42 from "figlet/importable-fonts/Big Money-sw.js";
import f43 from "figlet/importable-fonts/Big.js";
import f44 from "figlet/importable-fonts/Bigfig.js";
import f45 from "figlet/importable-fonts/Binary.js";
import f46 from "figlet/importable-fonts/Block.js";
import f47 from "figlet/importable-fonts/Blocks.js";
import f48 from "figlet/importable-fonts/Bloody.js";
import f49 from "figlet/importable-fonts/BlurVision ASCII.js";
import f50 from "figlet/importable-fonts/Bolger.js";
import f51 from "figlet/importable-fonts/Braced.js";
import f52 from "figlet/importable-fonts/Bright.js";
import f53 from "figlet/importable-fonts/Broadway KB.js";
import f54 from "figlet/importable-fonts/Broadway.js";
import f55 from "figlet/importable-fonts/Bubble.js";
import f56 from "figlet/importable-fonts/Bulbhead.js";
import f57 from "figlet/importable-fonts/Caligraphy.js";
import f58 from "figlet/importable-fonts/Caligraphy2.js";
import f59 from "figlet/importable-fonts/Calvin S.js";
import f60 from "figlet/importable-fonts/Cards.js";
import f61 from "figlet/importable-fonts/Catwalk.js";
import f62 from "figlet/importable-fonts/Chiseled.js";
import f63 from "figlet/importable-fonts/Chunky.js";
import f64 from "figlet/importable-fonts/Coinstak.js";
import f65 from "figlet/importable-fonts/Cola.js";
import f66 from "figlet/importable-fonts/Colossal.js";
import f67 from "figlet/importable-fonts/Computer.js";
import f68 from "figlet/importable-fonts/Contessa.js";
import f69 from "figlet/importable-fonts/Contrast.js";
import f70 from "figlet/importable-fonts/Cosmike.js";
import f71 from "figlet/importable-fonts/Cosmike2.js";
import f72 from "figlet/importable-fonts/Crawford.js";
import f73 from "figlet/importable-fonts/Crawford2.js";
import f74 from "figlet/importable-fonts/Crazy.js";
import f75 from "figlet/importable-fonts/Cricket.js";
import f76 from "figlet/importable-fonts/Cursive.js";
import f77 from "figlet/importable-fonts/Cyberlarge.js";
import f78 from "figlet/importable-fonts/Cybermedium.js";
import f79 from "figlet/importable-fonts/Cybersmall.js";
import f80 from "figlet/importable-fonts/Cygnet.js";
import f81 from "figlet/importable-fonts/DANC4.js";
import f82 from "figlet/importable-fonts/DOS Rebel.js";
import f83 from "figlet/importable-fonts/DWhistled.js";
import f84 from "figlet/importable-fonts/Dancing Font.js";
import f85 from "figlet/importable-fonts/Decimal.js";
import f86 from "figlet/importable-fonts/Def Leppard.js";
import f87 from "figlet/importable-fonts/Delta Corps Priest 1.js";
import f88 from "figlet/importable-fonts/DiamFont.js";
import f89 from "figlet/importable-fonts/Diamond.js";
import f90 from "figlet/importable-fonts/Diet Cola.js";
import f91 from "figlet/importable-fonts/Digital.js";
import f92 from "figlet/importable-fonts/Doh.js";
import f93 from "figlet/importable-fonts/Doom.js";
import f94 from "figlet/importable-fonts/Dot Matrix.js";
import f95 from "figlet/importable-fonts/Double Shorts.js";
import f96 from "figlet/importable-fonts/Double.js";
import f97 from "figlet/importable-fonts/Dr Pepper.js";
import f98 from "figlet/importable-fonts/Efti Chess.js";
import f99 from "figlet/importable-fonts/Efti Font.js";
import f100 from "figlet/importable-fonts/Efti Italic.js";
import f101 from "figlet/importable-fonts/Efti Piti.js";
import f102 from "figlet/importable-fonts/Efti Robot.js";
import f103 from "figlet/importable-fonts/Efti Wall.js";
import f104 from "figlet/importable-fonts/Efti Water.js";
import f105 from "figlet/importable-fonts/Electronic.js";
import f106 from "figlet/importable-fonts/Elite.js";
import f107 from "figlet/importable-fonts/Epic.js";
import f108 from "figlet/importable-fonts/Fender.js";
import f109 from "figlet/importable-fonts/Filter.js";
import f110 from "figlet/importable-fonts/Fire Font-k.js";
import f111 from "figlet/importable-fonts/Fire Font-s.js";
import f112 from "figlet/importable-fonts/Flipped.js";
import f113 from "figlet/importable-fonts/Flower Power.js";
import f114 from "figlet/importable-fonts/Four Tops.js";
import f115 from "figlet/importable-fonts/Fraktur.js";
import f116 from "figlet/importable-fonts/Fun Face.js";
import f117 from "figlet/importable-fonts/Fun Faces.js";
import f118 from "figlet/importable-fonts/Fuzzy.js";
import f119 from "figlet/importable-fonts/Georgi16.js";
import f120 from "figlet/importable-fonts/Georgia11.js";
import f121 from "figlet/importable-fonts/Ghost.js";
import f122 from "figlet/importable-fonts/Ghoulish.js";
import f123 from "figlet/importable-fonts/Glenyn.js";
import f124 from "figlet/importable-fonts/Goofy.js";
import f125 from "figlet/importable-fonts/Gothic.js";
import f126 from "figlet/importable-fonts/Graceful.js";
import f127 from "figlet/importable-fonts/Gradient.js";
import f128 from "figlet/importable-fonts/Graffiti.js";
import f129 from "figlet/importable-fonts/Greek.js";
import f130 from "figlet/importable-fonts/Heart Left.js";
import f131 from "figlet/importable-fonts/Heart Right.js";
import f132 from "figlet/importable-fonts/Henry 3D.js";
import f133 from "figlet/importable-fonts/Hex.js";
import f134 from "figlet/importable-fonts/Hieroglyphs.js";
import f135 from "figlet/importable-fonts/Hollywood.js";
import f136 from "figlet/importable-fonts/Horizontal Left.js";
import f137 from "figlet/importable-fonts/Horizontal Right.js";
import f138 from "figlet/importable-fonts/ICL-1900.js";
import f139 from "figlet/importable-fonts/Impossible.js";
import f140 from "figlet/importable-fonts/Invita.js";
import f141 from "figlet/importable-fonts/Isometric1.js";
import f142 from "figlet/importable-fonts/Isometric2.js";
import f143 from "figlet/importable-fonts/Isometric3.js";
import f144 from "figlet/importable-fonts/Isometric4.js";
import f145 from "figlet/importable-fonts/Italic.js";
import f146 from "figlet/importable-fonts/Ivrit.js";
import f147 from "figlet/importable-fonts/JS Block Letters.js";
import f148 from "figlet/importable-fonts/JS Bracket Letters.js";
import f149 from "figlet/importable-fonts/JS Capital Curves.js";
import f150 from "figlet/importable-fonts/JS Cursive.js";
import f151 from "figlet/importable-fonts/JS Stick Letters.js";
import f152 from "figlet/importable-fonts/Jacky.js";
import f153 from "figlet/importable-fonts/Jazmine.js";
import f154 from "figlet/importable-fonts/Jerusalem.js";
import f155 from "figlet/importable-fonts/Katakana.js";
import f156 from "figlet/importable-fonts/Kban.js";
import f157 from "figlet/importable-fonts/Keyboard.js";
import f158 from "figlet/importable-fonts/Knob.js";
import f159 from "figlet/importable-fonts/Konto Slant.js";
import f160 from "figlet/importable-fonts/Konto.js";
import f161 from "figlet/importable-fonts/LCD.js";
import f162 from "figlet/importable-fonts/Larry 3D 2.js";
import f163 from "figlet/importable-fonts/Larry 3D.js";
import f164 from "figlet/importable-fonts/Lean.js";
import f165 from "figlet/importable-fonts/Letters.js";
import f166 from "figlet/importable-fonts/Lil Devil.js";
import f167 from "figlet/importable-fonts/Line Blocks.js";
import f168 from "figlet/importable-fonts/Linux.js";
import f169 from "figlet/importable-fonts/Lockergnome.js";
import f170 from "figlet/importable-fonts/Madrid.js";
import f171 from "figlet/importable-fonts/Marquee.js";
import f172 from "figlet/importable-fonts/Maxfour.js";
import f173 from "figlet/importable-fonts/Merlin1.js";
import f174 from "figlet/importable-fonts/Merlin2.js";
import f175 from "figlet/importable-fonts/Mike.js";
import f176 from "figlet/importable-fonts/Mini.js";
import f177 from "figlet/importable-fonts/Mirror.js";
import f178 from "figlet/importable-fonts/Mnemonic.js";
import f179 from "figlet/importable-fonts/Modular.js";
import f180 from "figlet/importable-fonts/Morse.js";
import f181 from "figlet/importable-fonts/Morse2.js";
import f182 from "figlet/importable-fonts/Moscow.js";
import f183 from "figlet/importable-fonts/Mshebrew210.js";
import f184 from "figlet/importable-fonts/Muzzle.js";
import f185 from "figlet/importable-fonts/NScript.js";
import f186 from "figlet/importable-fonts/NT Greek.js";
import f187 from "figlet/importable-fonts/NV Script.js";
import f188 from "figlet/importable-fonts/Nancyj-Fancy.js";
import f189 from "figlet/importable-fonts/Nancyj-Improved.js";
import f190 from "figlet/importable-fonts/Nancyj-Underlined.js";
import f191 from "figlet/importable-fonts/Nancyj.js";
import f192 from "figlet/importable-fonts/Nipples.js";
import f193 from "figlet/importable-fonts/O8.js";
import f194 from "figlet/importable-fonts/OS2.js";
import f195 from "figlet/importable-fonts/Octal.js";
import f196 from "figlet/importable-fonts/Ogre.js";
import f197 from "figlet/importable-fonts/Old Banner.js";
import f198 from "figlet/importable-fonts/Pagga.js";
import f199 from "figlet/importable-fonts/Patorjk's Cheese.js";
import f200 from "figlet/importable-fonts/Patorjk-HeX.js";
import f201 from "figlet/importable-fonts/Pawp.js";
import f202 from "figlet/importable-fonts/Peaks Slant.js";
import f203 from "figlet/importable-fonts/Peaks.js";
import f204 from "figlet/importable-fonts/Pebbles.js";
import f205 from "figlet/importable-fonts/Pepper.js";
import f206 from "figlet/importable-fonts/Poison.js";
import f207 from "figlet/importable-fonts/Puffy.js";
import f208 from "figlet/importable-fonts/Puzzle.js";
import f209 from "figlet/importable-fonts/Pyramid.js";
import f210 from "figlet/importable-fonts/Rammstein.js";
import f211 from "figlet/importable-fonts/Rectangles.js";
import f212 from "figlet/importable-fonts/Red Phoenix.js";
import f213 from "figlet/importable-fonts/Relief.js";
import f214 from "figlet/importable-fonts/Relief2.js";
import f215 from "figlet/importable-fonts/Reverse.js";
import f216 from "figlet/importable-fonts/Roman.js";
import f217 from "figlet/importable-fonts/Rot13.js";
import f218 from "figlet/importable-fonts/Rotated.js";
import f219 from "figlet/importable-fonts/Rounded.js";
import f220 from "figlet/importable-fonts/Rowan Cap.js";
import f221 from "figlet/importable-fonts/Rozzo.js";
import f222 from "figlet/importable-fonts/RubiFont.js";
import f223 from "figlet/importable-fonts/Runic.js";
import f224 from "figlet/importable-fonts/Runyc.js";
import f225 from "figlet/importable-fonts/S Blood.js";
import f226 from "figlet/importable-fonts/SL Script.js";
import f227 from "figlet/importable-fonts/Santa Clara.js";
import f228 from "figlet/importable-fonts/Script.js";
import f229 from "figlet/importable-fonts/Serifcap.js";
import f230 from "figlet/importable-fonts/Shaded Blocky.js";
import f231 from "figlet/importable-fonts/Shadow.js";
import f232 from "figlet/importable-fonts/Shimrod.js";
import f233 from "figlet/importable-fonts/Short.js";
import f234 from "figlet/importable-fonts/Slant Relief.js";
import f235 from "figlet/importable-fonts/Slant.js";
import f236 from "figlet/importable-fonts/Slide.js";
import f237 from "figlet/importable-fonts/Small Caps.js";
import f238 from "figlet/importable-fonts/Small Isometric1.js";
import f239 from "figlet/importable-fonts/Small Keyboard.js";
import f240 from "figlet/importable-fonts/Small Poison.js";
import f241 from "figlet/importable-fonts/Small Script.js";
import f242 from "figlet/importable-fonts/Small Shadow.js";
import f243 from "figlet/importable-fonts/Small Slant.js";
import f244 from "figlet/importable-fonts/Small Tengwar.js";
import f245 from "figlet/importable-fonts/Small.js";
import f246 from "figlet/importable-fonts/Soft.js";
import f247 from "figlet/importable-fonts/Speed.js";
import f248 from "figlet/importable-fonts/Spliff.js";
import f249 from "figlet/importable-fonts/Stacey.js";
import f250 from "figlet/importable-fonts/Stampate.js";
import f251 from "figlet/importable-fonts/Stampatello.js";
import f252 from "figlet/importable-fonts/Standard.js";
import f253 from "figlet/importable-fonts/Star Strips.js";
import f254 from "figlet/importable-fonts/Star Wars.js";
import f255 from "figlet/importable-fonts/Stellar.js";
import f256 from "figlet/importable-fonts/Stforek.js";
import f257 from "figlet/importable-fonts/Stick Letters.js";
import f258 from "figlet/importable-fonts/Stop.js";
import f259 from "figlet/importable-fonts/Straight.js";
import f260 from "figlet/importable-fonts/Stronger Than All.js";
import f261 from "figlet/importable-fonts/Sub-Zero.js";
import f262 from "figlet/importable-fonts/Swamp Land.js";
import f263 from "figlet/importable-fonts/Swan.js";
import f264 from "figlet/importable-fonts/Sweet.js";
import f265 from "figlet/importable-fonts/THIS.js";
import f266 from "figlet/importable-fonts/Tanja.js";
import f267 from "figlet/importable-fonts/Tengwar.js";
import f268 from "figlet/importable-fonts/Term.js";
import f269 from "figlet/importable-fonts/Test1.js";
import f270 from "figlet/importable-fonts/The Edge.js";
import f271 from "figlet/importable-fonts/Thick.js";
import f272 from "figlet/importable-fonts/Thin.js";
import f273 from "figlet/importable-fonts/Thorned.js";
import f274 from "figlet/importable-fonts/Three Point.js";
import f275 from "figlet/importable-fonts/Ticks Slant.js";
import f276 from "figlet/importable-fonts/Ticks.js";
import f277 from "figlet/importable-fonts/Tiles.js";
import f278 from "figlet/importable-fonts/Tinker-Toy.js";
import f279 from "figlet/importable-fonts/Tombstone.js";
import f280 from "figlet/importable-fonts/Train.js";
import f281 from "figlet/importable-fonts/Trek.js";
import f282 from "figlet/importable-fonts/Tsalagi.js";
import f283 from "figlet/importable-fonts/Tubular.js";
import f284 from "figlet/importable-fonts/Twisted.js";
import f285 from "figlet/importable-fonts/Two Point.js";
import f286 from "figlet/importable-fonts/USA Flag.js";
import f287 from "figlet/importable-fonts/Univers.js";
import f288 from "figlet/importable-fonts/Varsity.js";
import f289 from "figlet/importable-fonts/Wavy.js";
import f290 from "figlet/importable-fonts/Weird.js";
import f291 from "figlet/importable-fonts/Wet Letter.js";
import f292 from "figlet/importable-fonts/Whimsy.js";
import f293 from "figlet/importable-fonts/Wow.js";
import f294 from "figlet/importable-fonts/miniwi.js";

import figlet from "figlet/lib/figlet.js";

// Register all fonts with figlet (filesystem-free, works in compiled binaries)
figlet.parseFont("1Row", f0);
figlet.parseFont("3-D", f1);
figlet.parseFont("3D Diagonal", f2);
figlet.parseFont("3D-ASCII", f3);
figlet.parseFont("3x5", f4);
figlet.parseFont("4Max", f5);
figlet.parseFont("5 Line Oblique", f6);
figlet.parseFont("AMC 3 Line", f7);
figlet.parseFont("AMC 3 Liv1", f8);
figlet.parseFont("AMC AAA01", f9);
figlet.parseFont("AMC Neko", f10);
figlet.parseFont("AMC Razor", f11);
figlet.parseFont("AMC Razor2", f12);
figlet.parseFont("AMC Slash", f13);
figlet.parseFont("AMC Slider", f14);
figlet.parseFont("AMC Thin", f15);
figlet.parseFont("AMC Tubes", f16);
figlet.parseFont("AMC Untitled", f17);
figlet.parseFont("ANSI Regular", f18);
figlet.parseFont("ANSI Shadow", f19);
figlet.parseFont("ASCII New Roman", f20);
figlet.parseFont("Acrobatic", f21);
figlet.parseFont("Alligator", f22);
figlet.parseFont("Alligator2", f23);
figlet.parseFont("Alpha", f24);
figlet.parseFont("Alphabet", f25);
figlet.parseFont("Arrows", f26);
figlet.parseFont("Avatar", f27);
figlet.parseFont("B1FF", f28);
figlet.parseFont("Banner", f29);
figlet.parseFont("Banner3-D", f30);
figlet.parseFont("Banner3", f31);
figlet.parseFont("Banner4", f32);
figlet.parseFont("Barbwire", f33);
figlet.parseFont("Basic", f34);
figlet.parseFont("Bear", f35);
figlet.parseFont("Bell", f36);
figlet.parseFont("Benjamin", f37);
figlet.parseFont("Big Chief", f38);
figlet.parseFont("Big Money-ne", f39);
figlet.parseFont("Big Money-nw", f40);
figlet.parseFont("Big Money-se", f41);
figlet.parseFont("Big Money-sw", f42);
figlet.parseFont("Big", f43);
figlet.parseFont("Bigfig", f44);
figlet.parseFont("Binary", f45);
figlet.parseFont("Block", f46);
figlet.parseFont("Blocks", f47);
figlet.parseFont("Bloody", f48);
figlet.parseFont("BlurVision ASCII", f49);
figlet.parseFont("Bolger", f50);
figlet.parseFont("Braced", f51);
figlet.parseFont("Bright", f52);
figlet.parseFont("Broadway KB", f53);
figlet.parseFont("Broadway", f54);
figlet.parseFont("Bubble", f55);
figlet.parseFont("Bulbhead", f56);
figlet.parseFont("Caligraphy", f57);
figlet.parseFont("Caligraphy2", f58);
figlet.parseFont("Calvin S", f59);
figlet.parseFont("Cards", f60);
figlet.parseFont("Catwalk", f61);
figlet.parseFont("Chiseled", f62);
figlet.parseFont("Chunky", f63);
figlet.parseFont("Coinstak", f64);
figlet.parseFont("Cola", f65);
figlet.parseFont("Colossal", f66);
figlet.parseFont("Computer", f67);
figlet.parseFont("Contessa", f68);
figlet.parseFont("Contrast", f69);
figlet.parseFont("Cosmike", f70);
figlet.parseFont("Cosmike2", f71);
figlet.parseFont("Crawford", f72);
figlet.parseFont("Crawford2", f73);
figlet.parseFont("Crazy", f74);
figlet.parseFont("Cricket", f75);
figlet.parseFont("Cursive", f76);
figlet.parseFont("Cyberlarge", f77);
figlet.parseFont("Cybermedium", f78);
figlet.parseFont("Cybersmall", f79);
figlet.parseFont("Cygnet", f80);
figlet.parseFont("DANC4", f81);
figlet.parseFont("DOS Rebel", f82);
figlet.parseFont("DWhistled", f83);
figlet.parseFont("Dancing Font", f84);
figlet.parseFont("Decimal", f85);
figlet.parseFont("Def Leppard", f86);
figlet.parseFont("Delta Corps Priest 1", f87);
figlet.parseFont("DiamFont", f88);
figlet.parseFont("Diamond", f89);
figlet.parseFont("Diet Cola", f90);
figlet.parseFont("Digital", f91);
figlet.parseFont("Doh", f92);
figlet.parseFont("Doom", f93);
figlet.parseFont("Dot Matrix", f94);
figlet.parseFont("Double Shorts", f95);
figlet.parseFont("Double", f96);
figlet.parseFont("Dr Pepper", f97);
figlet.parseFont("Efti Chess", f98);
figlet.parseFont("Efti Font", f99);
figlet.parseFont("Efti Italic", f100);
figlet.parseFont("Efti Piti", f101);
figlet.parseFont("Efti Robot", f102);
figlet.parseFont("Efti Wall", f103);
figlet.parseFont("Efti Water", f104);
figlet.parseFont("Electronic", f105);
figlet.parseFont("Elite", f106);
figlet.parseFont("Epic", f107);
figlet.parseFont("Fender", f108);
figlet.parseFont("Filter", f109);
figlet.parseFont("Fire Font-k", f110);
figlet.parseFont("Fire Font-s", f111);
figlet.parseFont("Flipped", f112);
figlet.parseFont("Flower Power", f113);
figlet.parseFont("Four Tops", f114);
figlet.parseFont("Fraktur", f115);
figlet.parseFont("Fun Face", f116);
figlet.parseFont("Fun Faces", f117);
figlet.parseFont("Fuzzy", f118);
figlet.parseFont("Georgi16", f119);
figlet.parseFont("Georgia11", f120);
figlet.parseFont("Ghost", f121);
figlet.parseFont("Ghoulish", f122);
figlet.parseFont("Glenyn", f123);
figlet.parseFont("Goofy", f124);
figlet.parseFont("Gothic", f125);
figlet.parseFont("Graceful", f126);
figlet.parseFont("Gradient", f127);
figlet.parseFont("Graffiti", f128);
figlet.parseFont("Greek", f129);
figlet.parseFont("Heart Left", f130);
figlet.parseFont("Heart Right", f131);
figlet.parseFont("Henry 3D", f132);
figlet.parseFont("Hex", f133);
figlet.parseFont("Hieroglyphs", f134);
figlet.parseFont("Hollywood", f135);
figlet.parseFont("Horizontal Left", f136);
figlet.parseFont("Horizontal Right", f137);
figlet.parseFont("ICL-1900", f138);
figlet.parseFont("Impossible", f139);
figlet.parseFont("Invita", f140);
figlet.parseFont("Isometric1", f141);
figlet.parseFont("Isometric2", f142);
figlet.parseFont("Isometric3", f143);
figlet.parseFont("Isometric4", f144);
figlet.parseFont("Italic", f145);
figlet.parseFont("Ivrit", f146);
figlet.parseFont("JS Block Letters", f147);
figlet.parseFont("JS Bracket Letters", f148);
figlet.parseFont("JS Capital Curves", f149);
figlet.parseFont("JS Cursive", f150);
figlet.parseFont("JS Stick Letters", f151);
figlet.parseFont("Jacky", f152);
figlet.parseFont("Jazmine", f153);
figlet.parseFont("Jerusalem", f154);
figlet.parseFont("Katakana", f155);
figlet.parseFont("Kban", f156);
figlet.parseFont("Keyboard", f157);
figlet.parseFont("Knob", f158);
figlet.parseFont("Konto Slant", f159);
figlet.parseFont("Konto", f160);
figlet.parseFont("LCD", f161);
figlet.parseFont("Larry 3D 2", f162);
figlet.parseFont("Larry 3D", f163);
figlet.parseFont("Lean", f164);
figlet.parseFont("Letters", f165);
figlet.parseFont("Lil Devil", f166);
figlet.parseFont("Line Blocks", f167);
figlet.parseFont("Linux", f168);
figlet.parseFont("Lockergnome", f169);
figlet.parseFont("Madrid", f170);
figlet.parseFont("Marquee", f171);
figlet.parseFont("Maxfour", f172);
figlet.parseFont("Merlin1", f173);
figlet.parseFont("Merlin2", f174);
figlet.parseFont("Mike", f175);
figlet.parseFont("Mini", f176);
figlet.parseFont("Mirror", f177);
figlet.parseFont("Mnemonic", f178);
figlet.parseFont("Modular", f179);
figlet.parseFont("Morse", f180);
figlet.parseFont("Morse2", f181);
figlet.parseFont("Moscow", f182);
figlet.parseFont("Mshebrew210", f183);
figlet.parseFont("Muzzle", f184);
figlet.parseFont("NScript", f185);
figlet.parseFont("NT Greek", f186);
figlet.parseFont("NV Script", f187);
figlet.parseFont("Nancyj-Fancy", f188);
figlet.parseFont("Nancyj-Improved", f189);
figlet.parseFont("Nancyj-Underlined", f190);
figlet.parseFont("Nancyj", f191);
figlet.parseFont("Nipples", f192);
figlet.parseFont("O8", f193);
figlet.parseFont("OS2", f194);
figlet.parseFont("Octal", f195);
figlet.parseFont("Ogre", f196);
figlet.parseFont("Old Banner", f197);
figlet.parseFont("Pagga", f198);
figlet.parseFont("Patorjk's Cheese", f199);
figlet.parseFont("Patorjk-HeX", f200);
figlet.parseFont("Pawp", f201);
figlet.parseFont("Peaks Slant", f202);
figlet.parseFont("Peaks", f203);
figlet.parseFont("Pebbles", f204);
figlet.parseFont("Pepper", f205);
figlet.parseFont("Poison", f206);
figlet.parseFont("Puffy", f207);
figlet.parseFont("Puzzle", f208);
figlet.parseFont("Pyramid", f209);
figlet.parseFont("Rammstein", f210);
figlet.parseFont("Rectangles", f211);
figlet.parseFont("Red Phoenix", f212);
figlet.parseFont("Relief", f213);
figlet.parseFont("Relief2", f214);
figlet.parseFont("Reverse", f215);
figlet.parseFont("Roman", f216);
figlet.parseFont("Rot13", f217);
figlet.parseFont("Rotated", f218);
figlet.parseFont("Rounded", f219);
figlet.parseFont("Rowan Cap", f220);
figlet.parseFont("Rozzo", f221);
figlet.parseFont("RubiFont", f222);
figlet.parseFont("Runic", f223);
figlet.parseFont("Runyc", f224);
figlet.parseFont("S Blood", f225);
figlet.parseFont("SL Script", f226);
figlet.parseFont("Santa Clara", f227);
figlet.parseFont("Script", f228);
figlet.parseFont("Serifcap", f229);
figlet.parseFont("Shaded Blocky", f230);
figlet.parseFont("Shadow", f231);
figlet.parseFont("Shimrod", f232);
figlet.parseFont("Short", f233);
figlet.parseFont("Slant Relief", f234);
figlet.parseFont("Slant", f235);
figlet.parseFont("Slide", f236);
figlet.parseFont("Small Caps", f237);
figlet.parseFont("Small Isometric1", f238);
figlet.parseFont("Small Keyboard", f239);
figlet.parseFont("Small Poison", f240);
figlet.parseFont("Small Script", f241);
figlet.parseFont("Small Shadow", f242);
figlet.parseFont("Small Slant", f243);
figlet.parseFont("Small Tengwar", f244);
figlet.parseFont("Small", f245);
figlet.parseFont("Soft", f246);
figlet.parseFont("Speed", f247);
figlet.parseFont("Spliff", f248);
figlet.parseFont("Stacey", f249);
figlet.parseFont("Stampate", f250);
figlet.parseFont("Stampatello", f251);
figlet.parseFont("Standard", f252);
figlet.parseFont("Star Strips", f253);
figlet.parseFont("Star Wars", f254);
figlet.parseFont("Stellar", f255);
figlet.parseFont("Stforek", f256);
figlet.parseFont("Stick Letters", f257);
figlet.parseFont("Stop", f258);
figlet.parseFont("Straight", f259);
figlet.parseFont("Stronger Than All", f260);
figlet.parseFont("Sub-Zero", f261);
figlet.parseFont("Swamp Land", f262);
figlet.parseFont("Swan", f263);
figlet.parseFont("Sweet", f264);
figlet.parseFont("THIS", f265);
figlet.parseFont("Tanja", f266);
figlet.parseFont("Tengwar", f267);
figlet.parseFont("Term", f268);
figlet.parseFont("Test1", f269);
figlet.parseFont("The Edge", f270);
figlet.parseFont("Thick", f271);
figlet.parseFont("Thin", f272);
figlet.parseFont("Thorned", f273);
figlet.parseFont("Three Point", f274);
figlet.parseFont("Ticks Slant", f275);
figlet.parseFont("Ticks", f276);
figlet.parseFont("Tiles", f277);
figlet.parseFont("Tinker-Toy", f278);
figlet.parseFont("Tombstone", f279);
figlet.parseFont("Train", f280);
figlet.parseFont("Trek", f281);
figlet.parseFont("Tsalagi", f282);
figlet.parseFont("Tubular", f283);
figlet.parseFont("Twisted", f284);
figlet.parseFont("Two Point", f285);
figlet.parseFont("USA Flag", f286);
figlet.parseFont("Univers", f287);
figlet.parseFont("Varsity", f288);
figlet.parseFont("Wavy", f289);
figlet.parseFont("Weird", f290);
figlet.parseFont("Wet Letter", f291);
figlet.parseFont("Whimsy", f292);
figlet.parseFont("Wow", f293);
figlet.parseFont("miniwi", f294);

export { figlet };
export const fontNames: string[] = ["1Row","3-D","3D Diagonal","3D-ASCII","3x5","4Max","5 Line Oblique","AMC 3 Line","AMC 3 Liv1","AMC AAA01","AMC Neko","AMC Razor","AMC Razor2","AMC Slash","AMC Slider","AMC Thin","AMC Tubes","AMC Untitled","ANSI Regular","ANSI Shadow","ASCII New Roman","Acrobatic","Alligator","Alligator2","Alpha","Alphabet","Arrows","Avatar","B1FF","Banner","Banner3-D","Banner3","Banner4","Barbwire","Basic","Bear","Bell","Benjamin","Big Chief","Big Money-ne","Big Money-nw","Big Money-se","Big Money-sw","Big","Bigfig","Binary","Block","Blocks","Bloody","BlurVision ASCII","Bolger","Braced","Bright","Broadway KB","Broadway","Bubble","Bulbhead","Caligraphy","Caligraphy2","Calvin S","Cards","Catwalk","Chiseled","Chunky","Coinstak","Cola","Colossal","Computer","Contessa","Contrast","Cosmike","Cosmike2","Crawford","Crawford2","Crazy","Cricket","Cursive","Cyberlarge","Cybermedium","Cybersmall","Cygnet","DANC4","DOS Rebel","DWhistled","Dancing Font","Decimal","Def Leppard","Delta Corps Priest 1","DiamFont","Diamond","Diet Cola","Digital","Doh","Doom","Dot Matrix","Double Shorts","Double","Dr Pepper","Efti Chess","Efti Font","Efti Italic","Efti Piti","Efti Robot","Efti Wall","Efti Water","Electronic","Elite","Epic","Fender","Filter","Fire Font-k","Fire Font-s","Flipped","Flower Power","Four Tops","Fraktur","Fun Face","Fun Faces","Fuzzy","Georgi16","Georgia11","Ghost","Ghoulish","Glenyn","Goofy","Gothic","Graceful","Gradient","Graffiti","Greek","Heart Left","Heart Right","Henry 3D","Hex","Hieroglyphs","Hollywood","Horizontal Left","Horizontal Right","ICL-1900","Impossible","Invita","Isometric1","Isometric2","Isometric3","Isometric4","Italic","Ivrit","JS Block Letters","JS Bracket Letters","JS Capital Curves","JS Cursive","JS Stick Letters","Jacky","Jazmine","Jerusalem","Katakana","Kban","Keyboard","Knob","Konto Slant","Konto","LCD","Larry 3D 2","Larry 3D","Lean","Letters","Lil Devil","Line Blocks","Linux","Lockergnome","Madrid","Marquee","Maxfour","Merlin1","Merlin2","Mike","Mini","Mirror","Mnemonic","Modular","Morse","Morse2","Moscow","Mshebrew210","Muzzle","NScript","NT Greek","NV Script","Nancyj-Fancy","Nancyj-Improved","Nancyj-Underlined","Nancyj","Nipples","O8","OS2","Octal","Ogre","Old Banner","Pagga","Patorjk's Cheese","Patorjk-HeX","Pawp","Peaks Slant","Peaks","Pebbles","Pepper","Poison","Puffy","Puzzle","Pyramid","Rammstein","Rectangles","Red Phoenix","Relief","Relief2","Reverse","Roman","Rot13","Rotated","Rounded","Rowan Cap","Rozzo","RubiFont","Runic","Runyc","S Blood","SL Script","Santa Clara","Script","Serifcap","Shaded Blocky","Shadow","Shimrod","Short","Slant Relief","Slant","Slide","Small Caps","Small Isometric1","Small Keyboard","Small Poison","Small Script","Small Shadow","Small Slant","Small Tengwar","Small","Soft","Speed","Spliff","Stacey","Stampate","Stampatello","Standard","Star Strips","Star Wars","Stellar","Stforek","Stick Letters","Stop","Straight","Stronger Than All","Sub-Zero","Swamp Land","Swan","Sweet","THIS","Tanja","Tengwar","Term","Test1","The Edge","Thick","Thin","Thorned","Three Point","Ticks Slant","Ticks","Tiles","Tinker-Toy","Tombstone","Train","Trek","Tsalagi","Tubular","Twisted","Two Point","USA Flag","Univers","Varsity","Wavy","Weird","Wet Letter","Whimsy","Wow","miniwi"];
